services:
  mysql:
    image: mysql:8.0
    container_name: lxp-mysql
    restart: always
    environment:
      MYSQL_DATABASE: lxp
      MYSQL_USER: lxp
      MYSQL_PASSWORD: lxp
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: Asia/Seoul
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  app:
    image: youable/lxp-project-3th:0.0.2
    container_name: lxp-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "6001:8080"

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - ./init/seed.redis:/data/seed.redis
    command: >
      sh -c "redis-server --appendonly yes &
             sleep 2 &&
             redis-cli < /data/seed.redis &&
             echo 'Seed loaded' &&
             wait"

volumes:
  mysql_data:
  redis-data: